virt-lightning/virt-lightning

setup.py
virt_lightning/__init__.py
virt_lightning/shell.py
virt_lightning/symbols.py
virt_lightning/templates.py

I did some checks and added string formatting.

Some improvments

---

.travis.yml
requirements.txt

See: https://github.com/virt-lightning/virt-lightning/pull/4#issuecomment-463175140

add libvirt-python in the requirements.txt

---

README.md
images/centos-7.sh
images/debian-9.sh
images/defines
images/distros/centos-7
images/distros/debian-9
images/distros/fedora-29
images/distros/rhel-7.4
images/distros/rhel-7.5
images/distros/rhel-7.6
images/distros/ubuntu-16.04
images/distros/ubuntu-18.04
images/fedora-29.sh
images/image
images/rhel-7.4.sh
images/rhel-7.5.sh
images/rhel-7.6.sh
images/ubuntu-16.04.sh
images/ubuntu-18.04.sh
requirements.txt

More flexible script to work over images.

Added more flexable image script to work over images

---

README.md

We now depend on libvirt-python in the requirements.txt.

doc: use libvirt-python

---

images/defines
virt_lightning/__init__.py
virt_lightning/shell.py
virt_lightning/templates.py

Until now, only generic users were supported.

Support root user

---

.gitignore
README.md
conf/example.ini
virt_lightning/__init__.py
virt_lightning/configuration.py
virt_lightning/shell.py

* Updated README.md
* Added .gitignore file
* Added new class to read config file and parse from *.ini file
* Redo code to use object properties instead dict access to the object of config

Added support load configuration from file:

---

virt_lightning/__init__.py

Look-up several kvm potential location to find which one to use.

dynamically adjust the path to qemu-kvm

---

virt_lightning/__init__.py
virt_lightning/configuration.py
virt_lightning/shell.py

Ensure `tox` runs fine without any error. I'm not sure why Travis didn't
report the problem.

flake8 and black fixes

---

ansible/playbook.yml
ansible/roles/virt_lightning/tasks/image.yml
ansible/roles/virt_lightning/tasks/install.yml
ansible/roles/virt_lightning/tasks/main.yml
ansible/roles/virt_lightning/tasks/test.yml
ansible/roles/virt_lightning/templates/pool.xml.j2
ansible/test.sh
ansible/virt-lightning.yaml

The end-to-end test is currently broken because the inner libvirt use the 192.168.124.0/24 network when we expect 192.168.122.0/24.

use Ansible to do end-to-end testing

---

ansible/playbook.yml
ansible/virt-lightning.yaml
virt_lightning/shell.py

- increase the amount of memory of the guest to 3000MB
- fix the create_domain, to it won't fail because host has an extra key
that is ignored
- ssh_ping(): SSH key checking is irrelevant in our context

ansible: end-to-end test

---

virt_lightning/__init__.py
virt_lightning/shell.py

Lookup the disks of the domain and use the libvirt API to delete them.
The users may not be allowed to delete the disk by themselves.

clean_up: also delete the domain disk files

---

tests/conftest.py
virt_lightning/__init__.py
virt_lightning/templates.py

Progress toward the full support of qemu:///system for the users.

Support qemu:///system URI

---

virt_lightning/__init__.py
virt_lightning/shell.py

Improve the way we purge domains:
- also remove all the associated files
- and the managed save/snapshots

Improve the purge of the domain

---

virt_lightning/configuration.py
virt_lightning/shell.py

- use argparse's subparser to handle the different actions
- let argparse handle the parsing/validation of virt_lightning_yaml
- simplify a bit the logic of Configuration

simplify the argument parsing

---

ansible/roles/virt_lightning/tasks/image.yml
images/distros/centos-7
images/distros/debian-9
images/distros/fedora-29
images/distros/rhel-7.4
images/distros/rhel-7.5
images/distros/rhel-7.6
images/distros/ubuntu-16.04
images/distros/ubuntu-18.04

If `$MIRROR_URL` is defined, we use it.

image: ability to use a mirror

---

virt_lightning/shell.py
virt_lightning/virt_lightning.py

Use a `property` decorator instead of the if/else block.

simplify the logic used to set the root password

---

virt_lightning/virt_lightning.py

Actually /usr/bin/qemu-system-x86_64 should be enough.

kvm path: add /usr/bin/qemu-system-x86_64

---

.gitignore

Ignore cache of mypy and pytest.

refresh the .gitignore file

---

test-requirements.txt
tox.ini
virt_lightning/shell.py
virt_lightning/symbols.py
virt_lightning/ui.py
virt_lightning/virt_lightning.py

Do not unconditionally import libvirtaio in virt_lightning.py.

conditional loading of libvirtaio

---

.gitignore
README.md
virt-lightning.yaml
virt_lightning/shell.py
virt_lightning/symbols.py
virt_lightning/virt_lightning.py

* Added new symbols to enum mapping
* Removed virt-lightning.yaml from repository (file requires build new one before run commands)
* Added vrit-lightning.yaml to .gitignore
* Added to README information about Ubuntu to build images

Fixing some issues with symbols and inventory

---

virt_lightning/shell.py
virt_lightning/virt_lightning.py

ability to set group of machines

---

virt_lightning/shell.py
virt_lightning/virt_lightning.py

ESXi only allow connection with the root user.
Note: it would be better to have a configuration file
per distro.

ansible: format the inventory depending on the distro

---

images/distros/rhel-8.0

RHEL 8 is out

---

virt_lightning/templates.py
virt_lightning/virt_lightning.py

Add DHCP record on the fly, this allow the use of DHCP during the boot.

set the DHCP entry on the fly

---

virt_lightning/shell.py
virt_lightning/virt_lightning.py

These actions can be used to start/stop only one VM.

add start and stop actions

---

images/distros/fedora-30

- fedora-30
Tested and it works fine :)

add new images

---

README.md
virt_lightning/shell.py

`vl fetch $foo` allow the user to quickly import an existing image.

add Fetch action

---

tests/conftest.py
tests/test_configure.py
virt_lightning/configuration.py
virt_lightning/shell.py
virt_lightning/virt_lightning.py

Improve the warning message.
Depends-On: https://github.com/virt-lightning/virt-lightning/pull/106

Low memory warning

---

virt_lightning/shell.py

Generate ssh.config with current running instances
Fixes #112

Add ssh_config CLI command

---

README.md
virt_lightning/shell.py
virt_lightning/virt_lightning.py

- the IP has to be in the correct range
- only works with the primary NIC

ability to manually set the IP address

---

virt_lightning/shell.py
virt_lightning/templates.py
virt_lightning/virt_lightning.py

- add a new optional `fqdn` key
- rename `clouud_init` attribute `user_data` for clarity
- rename `CLOUD_INIT_ENI` to `META_DATA_ENI` for the same reason

ability to set the FQDN

---

tox.ini
virt_lightning/__init__.py
virt_lightning/virt_lightning.py

Introduce the use of type annotation to spot this kind of problem
faster.

ensure get_distro_configuration() return dict

---

tests/test_hv.py
virt_lightning/templates.py
virt_lightning/virt_lightning.py

- don't try to guess, but actually look for the XML section that have to be
cleaned up
- do not use the same method to create and clean up the network, it was
over-complicated

static DNS/DHCP refactoring

---

README.md

Doc should explain how to install the stable version, not devel.

doc: install the stable version by default

---

virt_lightning/shell.py
virt_lightning/ui.py
virt_lightning/virt_lightning.py

Take into account most of the lgtm.com warnings.

clean of warning reported by LGTM

---

azure-pipelines.yml

azure-pipelines, remove py3.5 from

---

virt_lightning/configuration.py
virt_lightning/shell.py

Quick and easy change to make the configuration option more descriptive.

Rename network_del to network_auto_clean_up

---

README.md

Document the new network_auto_clean_up configuration option.
Add basic directions for using virt-lightning on a Void Linux host.

Document config.ini change and Void Linux setup

---

virt_lightning/shell.py

The output, especially in tmux, is pretty jumbled and messy. I'd prefer to have it disabled by default, but I don't know the general use-cases people have for `start`. I left the current default behavior alone.

Add --noconsole to suppress console output when creating a one-off VM

---

virt_lightning/shell.py

When using `virt_lightning` programmatically, I've encountered that `shell.up()` can not be called twice from the same program; attempting to do so produces traceback similar to 
```
File "...venv/lib64/python3.7/site-packages/virt_lightning/shell.py", line 92, in up
libvirtaio.virEventRegisterAsyncIOImpl(loop=loop)
File "...venv/lib64/python3.7/site-packages/libvirtaio.py", line 456, in virEventRegisterAsyncIOImpl
_current_impl = virEventAsyncIOImpl(loop=loop).register()
File "...venv/lib64/python3.7/site-packages/libvirtaio.py", line 302, in register
self._add_timeout, self._update_timeout, self._remove_timeout)
File "...venv/lib64/python3.7/site-packages/libvirt.py", line 346, in virEventRegisterImpl
libvirtmod.virEventRegisterImpl(addHandle, updateHandle, removeHandle, addTimeout, …
```

make sure shell.up() is allowed to be called twice programmatically

---

README.md

They are confusing, people don't unfold the sections.

README: remove the foldable blocks

---

images/distros/centos-8

Well, everything is in the title !

Add centos-8 image

---

virt_lightning/api.py

Log the address of the final URL.

fetch: log the HTTP redirection

---

virt_lightning/api.py

Log the `Last-Modified` and `Content-Length` fields.

api/fetch: log some information about image

---

virt-lightning.org/bench_images_startup.py

Enable the logger at level DEBUG.

bench_images_startup: turn on the logger

---

virt_lightning/api.py
virt_lightning/shell.py

Use exception to raise problem in `api.py`. Also, reduce the amount of log produced in `api.py`.

shell: handle exception from api.py

---

virt_lightning/shell.py

refresh formatting

---

virt-lightning.org/bench_images_startup.py

bench_images_startup.py: sum is a float

---

virt_lightning/templates.py
virt_lightning/virt_lightning.py

Improve the existing message to correctly fix the privilege of the
upstream directory.

explain how to set the upstream folder privilege

---

virt_lightning/api.py
virt_lightning/shell.py

Show up a better message when libvirt cannot connect to
qemu:///system.

better msg if user cannot connect to libvirt

---

virt_lightning/api.py
virt_lightning/shell.py

Show up a better message to explain the situation when an instance
already exists but is not running.

better message if VM exists but is off

---

virt_lightning/shell.py

Add missing "distro" parameter to distro_list output

---

README.md
virt_lightning/virt_lightning.py

Hi @goneri!
Please let me know whatever you need changed in this PR.
Cheers!
Closes: https://github.com/virt-lightning/virt-lightning/issues/217

Feature #217: Add ovsbr support

---

README.md

README.md: Add notice about ssh_key_file

---

virt_lightning/api.py
virt_lightning/shell.py

Add command documentation

---

virt_lightning/templates.py

Change Spice to VNC

---

.github/workflows/tests.yml

Remove obsolete Python versions and enable 3.10

Groom Github Actions

---

changelog.md
setup.py

prepare 2.2.0 release

---

virt_lightning/api.py
virt_lightning/shell.py

Add the ability:
- to adjust the size of the disk
- add more disks

vl start: add --disk argument

---

virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf
virt-lightning.org/www/images/index.md

Hello,
I just came across this project and it is awesome. But i missed some images. This PR is an attempt to add these images to the project.

added support for debian-11 and rockylinux-8 and rockylinux-9

---

virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf
virt-lightning.org/www/images/index.md

- DragonFlyBSD 6.2.2
- OpenBSD 7.1
- OpenBSD 7.2
- Ubuntu 22.04
- Ubuntu 22.10

distro: add new images

---

virt_lightning/virt_lightning.py

Workaround for CloudInit, sources.helpers.openstack read the subnet DNS from
ths dns_nameservers and ignore the services key.
Also, with Fedora, CloudInit only apply the DNS from the subnet
and ignore the global one from the root services key.
This fix the DNS problem with NetworkManager (e.g: Fedora).

cloudinit: add a workaround for the DNS and Fedora

---

virt-lightning.org/bench_images_startup.py
virt_lightning/configuration.py
virt_lightning/virt_lightning.py

Converted string format calls which include operations to safer fstrings equivalents

Add fixes fo fstrings

---

README.md

Added some info how to save and VM  snapshots

Update README with snapshots example

---

.github/workflows/tests.yml

Renamed Tox env name in GH Actions job

---

pyproject.toml

Fixes: aedcb4be237b ("move from setup.py to pyproject.toml")

Remove duplicate protocol from Homepage URL

---

virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf
virt-lightning.org/www/images/index.md

Add Fedora 39 image

---

tox.ini

Also, configured Tox to use isolated build to make it compatible with pyproject.toml

Enabled Python 3.12 for tests

---

virt_lightning/virt_lightning.py

Make message more neat and clear

Fixed error message for missing genisoimage

---

virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf
virt-lightning.org/www/images/index.md

distro: add Debian 13 (Trixie)

---

virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf

Update the centos stream URL links to the latest version

update centos stream images

---

README.md
virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf
virt_lightning/shell.py

Update the Readme with a hint
Update the shell.py help response

Add commands

---

README.md
virt_lightning/api.py
virt_lightning/virt_lightning.py

Add additional network addresses to Ansible inventory

---

README.md

Add a note pointing user what to investigate in case of VM python version incompatible with the host Ansible

Inventory update in Readme

---

virt_lightning/templates.py
virt_lightning/virt_lightning.py

This is remain low and we may bump it again to 2GB soon.

config: bump the default memory from 768MB to 1024MB

---

virt-lightning.org/images.json

- remove opensuse leap 15.2
- add opensuse leap 15.6
- add opensuse tumbleweed and microos

update image list
