- README.md
- images/distros/centos-7
- images/distros/debian-9
- images/distros/fedora-29
- images/distros/rhel-7.4
- images/distros/rhel-7.5
- images/distros/rhel-7.6
- virt_lightning/__init__.py
- virt_lightning/shell.py
- virt_lightning/templates.py
DHCP slow thing down a lot (=~15s in a 9 nodes env). We this patch, the 
nodes network configuration is static.
The static IP addresses are recorded in the domain XMLs, this way, we
can do quickly list the IP already in use, even if the domain are not 
running.
Also:
- Centos-7: enable NetworkManager to be consistent with the RHEL-7
images
- Adjust the default configuration of the images to prevent any DHCP
auto-configuration
Others:
- do not call `systemctl mask cloud-init`, this was breaking cloud-init
at last in one environment.
- fix a little performance issue with the SSH ping
> network: avoid DHCP

- virt_lightning/__init__.py
libvirt will raise an exception if the VM is not active and we try to access
the agent.
> do not try to reach agent on inactive domain

- virt_lightning/templates.py
pc is an alias for the last, up to date architecture.
> use 'pc' as the default kvm machine

- virt_lightning/shell.py
Missing configuration argument from b679f5fcb986f97b13d8fa40fef476572611395b
Otherwise it will just fail
> Fix vl storage_dir command

- virt_lightning/__init__.py
- virt_lightning/shell.py
Create the domain with the final name, this to avoid the transitional
state where the VM has a temporary name.
> avoid domain with no name

- README.md
- conf/example.ini
- requirements.txt
- virt_lightning/__init__.py
- virt_lightning/configuration.py
- virt_lightning/shell.py
Collect the IPv4 configuration of the bridge interface and use it
for the definition of the guest network configuration.
closes: #17
> retrieve network configuration from libvirt net

- tests/test_foo.py
- tests/test_hv.py
- virt_lightning/__init__.py
- virt_lightning/configuration.py
- virt_lightning/shell.py
- virt_lightning/templates.py
With this patch, `virt-lightning` creates the  storage pool automatically.
In order to simplify the testing, the patch also:
- modifies the LibvirtHypervisor object initialization to avoid strong
relationship with the configuration object
- makes use of the pathlib objects
closes: #18
> dynamically create the storage pool

- images/distros/centos-7
- images/distros/debian-9
- images/distros/fedora-29
- images/distros/ubuntu-16.04
- images/distros/ubuntu-18.04
On Ubuntu 18.04, `virt-sysprep --network` creates an environmnet without
DNS resolution. This commit introduces a work around to avoid the problem.
See: https://bugs.launchpad.net/ubuntu/+source/libguestfs/+bug/1768085
> ensure we can build the images on Ubuntu

- virt_lightning/templates.py
Fix commit 18f5db889825d71cdcb189f8acc08607e156b976:
Put back:
- the qemu-guest-agent channel
- ensure the bridge XML description does not have any PCI address
> add missing entries in the domain XML

- virt_lightning/__init__.py
Since use `vl storage_dir` in Ansible, we cannot show up this kind of
debug message.
This is a temporary situation that will be resolved by #32.
> do not show anything when a pool is missing

- images/distros/debian-9
cloud-init uses a dns-nameservers key in /etc/network/interfaces.d/50-cloud-init.cfg
to configure the nameserver. This feature depends on resolvconf, we
have to install and configure it.
> debian: configure resolvconf

- virt_lightning/virt_lightning.py
Libvirt won't remove the volumes if the domain is still running.
> remove the storage volume after dom deletion

- images/distros/debian-10
This to speed up the start up of sshd.
See: https://unix.stackexchange.com/questions/442698/when-i-log-in-it-hangs-until-crng-init-done
> image: install haveged on Debian-10

- ansible/roles/virt_lightning/tasks/test.yml
- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
This to avoid the following error with libvirt 1.3.1 (Ubuntu 16.04):
libvirt.libvirtError: internal error: the caller doesn't support keepalive protocol; perhaps it's missing event loop implementation
See: https://www.redhat.com/archives/libvirt-users/2014-April/msg00011.html
> libvirt: virEventRegisterDefaultImpl() before open()

- virt_lightning/shell.py
Added missing character that remove the following stack:
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib64/python3.7/logging/__init__.py", line 1034, in emit
msg = self.format(record)
File "/usr/lib64/python3.7/logging/__init__.py", line 880, in format
return fmt.format(record)
File "/usr/lib64/python3.7/logging/__init__.py", line 619, in format
record.message = record.getMessage()
File "/usr/lib64/python3.7/logging/__init__.py", line 380, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
File "/usr/lib64/python3.7/threading.py", line 885, in _bootstrap
self._bootstrap_inner()
File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.7/threading.py", line …
> added missing string character

- virt_lightning/virt_lightning.py
Minor adjustment to avoid the following error with an up to date version
of libvirt:
```
libvirt.libvirtError: unsupported configuration: disk type 'virtio' of 'vdc' does not support ejectable media
```
See: https://marc.info/?l=libvir-list&m=154929531226510&w=2
> avoid: ejectable media cannot use virtio type

- virt_lightning/virt_lightning.py
Don't wrap the original exception in a new one.
> don't hide Python exception

- virt_lightning/virt_lightning.py
While doing some work I tried to add a vm with more then 2 vcpu and it failed with 
`libvirt.libvirtError: invalid argument: requested vcpus is greater than max allowable vcpus for the persistent domain: 4 > 2`
With this change the max number of vcpu in the template is set to the number of vcpu available to the host. Also if vcpus is not set in virt-lightning.yml it will default to 2 vcpus.
> permit more than 2 vcpus

- virt_lightning/shell.py
We don't need the exception for FreeBSD anymore. This VM default size is
much smaller now.
> root_disk_size: default at 15G again

- virt_lightning/shell.py
`vl start` do not ignore the `--memory` and `--vcpus` parameter anymore.
> start: pass --memory and --vcpus properly

- virt_lightning/shell.py
When no hostname is set, virt-lightning generates a new on based on
the name of the distro. With this change, itt won't strip the '-' character
from the distro name anymore.
> hostname autogeneration: allow - char

- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
- python_interpreter: come with sensible default settings
- ansible_inventory: set the root password and python_interpreter
- read the configuration keys from `virt-lightning.yaml`
> improve distro specific config managment

- virt_lightning/shell.py
- virt_lightning/templates.py
- virt_lightning/virt_lightning.py
- destroy the `virt-lightning` network at the end of the run.
- try harder to delete the existing DHCP/DNS record
- reduce the lease duration to be sure the IP will be quickly freed
> clean up the network

- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
OpenStack's network metadata is well supported and, this allow us to
remove a series of hack that was needed with the NoCloud format.
NoCloud is still the default for RHEL6 and CentOS6.
> use openstack metadata format by default

- README.md
- virt_lightning/virt_lightning.py
Ensure `virt-lightning` works on RHEL8:
- Add `/usr/libexec/qemu-kvm` in `KVM_BINARIES` list
- documentation the installation.
> on RHEL8, kvm is in /usr/libexec

- README.md
- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
- IP is attached to the first NIC by default
- default type is `virtio`
- add two new keys: `default_nic_model` and `nic_model` to overwrite the
default NIC driver (`virtio`)
> add ability to define several NIC

- tests/test_domain.py
- virt_lightning/templates.py
- virt_lightning/virt_lightning.py
Since 620ddeeaee52438bf984f5478fc5149575e60ae3, all the CPUs were
attached and active. Now we can still potentially increase the number
of the CPU, but only some of them are active (only the defined in `vcpus`).
> vcpu: correctly cap the number of CPU

- images/distros/centos-7
We don't need NetworkManager anymore with OpenStack metadata format:
d14a1dff265b49e841d3e147e693ed490282b1dc.
> centos: don't need NetworkManager anymore

- virt_lightning/shell.py
This way, we can set a specific name. e.g: `vl start --name foo centos-7`
> start: add the --name argument

- virt_lightning/virt_lightning.py
So far, we only define the maximum amount of memory for a VM. The
allocation was still at 768MB by default.
"If VIR_DOMAIN_MEM_MAXIMUM is set, the change affects domain's maximum
memory size rather than current memory size."
With this change, we ensure the VM get the amount of memory that we
expect.
See: https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetMemoryFlags
> memory: set the current the amount of memory

- virt_lightning/virt_lightning.py
See: https://blueprints.launchpad.net/cloud-init/+spec/set-image-root-password
> metadata: pass the root_password in `admin_pass`

- tests/test_domain.py
- virt_lightning/virt_lightning.py
Ensure the `fqdn` parameter can accept a string with `.`... :-)
> fix the fqdn parameter

- virt_lightning/shell.py
Refresh the documentation to cover the following actions:
- `up`
- `down`
- `status`
- `distro_list`
Closes: #129
> refresh the `--help` output

- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
Host may have no IP configuration, in this case, we just ignore it.
> remove_domain_from_network: ignore host with no IP

- virt_lightning/configuration.py
- virt_lightning/shell.py
Adds the configuration option 'network_del' with a default value of True. Gate destroying the network with a check of this configuration option, cast to a bool. This retains the previous behavior (unilaterally delete the network on vl down) as the default behavior.
I opted for this instead of checking if anything was still attached to the network - that method was going to add a substantial amount of overhead to handle the case of stopped VMs that still reference the network. For my use cases at least, I'll manually create the network virt-lightning uses and then it'll be permanent on the hypervisor.
> Issue #137

- virt_lightning/virt_lightning.py
genisoimage isn't available everywhere, but mkisofs seems to be directly
compatible with it (genisoimage was forked by Debian from mkisofs).
Add support to look for either tool in the PATH, preferring genisoimage
over mkisofs. No user configuration is required, with existing behavior
preserved.
Both ISO image generation paths were locally tested (dynamic IP, static defined in yaml) with no issues.
> Support multiple ISO generation tools

- virt_lightning/shell.py
Checking if the domain context matches the context from the command line should happen before the ansible groups arrays are built. This prevents hosts in the same ansible group from different contexts/projects slipping into a group definition.
With this change:
```
$ vl ansible_inventory --context project2
test-5 ansible_host=192.168.123.6 ansible_user=zdykstra ansible_python_interpreter=/usr/bin/python ansible_ssh_common_args="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
test-4 ansible_host=192.168.123.7 ansible_user=zdykstra ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
[test-centos]
test-5
[test-ubuntu]
test-4
$ vl ansible_inventory --context project1
test-3 ansible_host=192.168.123.85 …
```
> Check context before appending to ansible groups

- README.md
- virt_lightning/shell.py
Add the `viewer` command line option. This can be used to open a `virt-viewer` console for a domain. This is useful when you need to see what happens in a VM before the kernel starts.
It performs a single fork and closes stdout and stderr.
> Add in virt-viewer support

- virt_lightning/shell.py
Allow setting --context on the command line when starting a one-off virtual machine.
> Pass context to manually created VM

- tox.ini
Black code formatter tends to go slightly above the historical 80 characters
limit. We don't really need this flake8 check since Black will anyway check
the line lenght by itself.
See: https://github.com/psf/black#line-length
> flake8: ignore E501 line too long

- README.md
- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
honor the bootcmd config key
`bootcmd` commands are evaluated by cloud-init after the very first boot
of the VM.
See: https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot
> honor the bootcmd config key

- README.md
- tests/test_domain.py
- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
So far, it was possible to add extra NIC, but the ipv4 configuration was
ignore. This commit adds the ability to specific what statuc IPv4 should be
set.
See also: https://github.com/virt-lightning/virt-lightning/pull/153
Tested with the following configuration:
```yaml
- distro: centos-7
networks:
- ipv4: 192.168.123.50
- network: default
ipv4: 192.168.122.50
- network: foobar
- distro: centos-6
provider: nocloud
networks:
- ipv4: 192.168.123.51
- network: default
ipv4: 192.168.122.51
- network: foobar
```
Closes: #145
> ability to set the IP of the other nics

- virt_lightning/virt_lightning.py
Prevent `get_network_gateway()` from overwriting `self.network_obj`.
> get_network_gateway: do not overwrite self.network_obj

- virt_lightning/virt_lightning.py
No need to test ConnectionRefusedError and OSError as the same time.
> ConnectionRefusedError inherite from OSError

- virt_lightning/shell.py
Avoid the use of `print()` when `sys.stdout.write()` makes more sense.
> use sys.stdout.write() instead of print()

- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
Time to time, a VM is deleted, but its entry in the DHCP leases remains.
As a result, the DHCP won't give back the same IP until the lease as
expired.
We now reuse previously the same MAC for the new instance as soon as the
IP and the hostname are the same.
> recycle previous MAC

- virt_lightning/shell.py
The 'ipv4' key be unset. In this case, we just return `None` to avoid
the `KeyError` exception.
> reuse_mac_address: handle the case ipv4 is not set

- images/distros/centos-7
Small change in the guest sshd config. I noticed ssh timeouts when trying ansible-playbooks, this config change fixed that issue (and is recommended for guest instances, no clue why it's not by default yet for cloud images)
> CentOS7: improve ssh performances

- changelog.md
- tox.ini
- virt_lightning/api.py
- virt_lightning/shell.py
- virt_lightning/virt_lightning.py
Split up the content of `shell.py` in two parts.
- `api.py`: a generic module than can be reused by anyone
- `shell.py`: a CLI that consume `api.py`.
> refactoring: introduce API module

- virt-lightning.org/bench_images_startup.py
distro is not a named argument anymore.
> bench_images_startup.py: Surplus named argument for string format.

- virt_lightning/api.py
- virt_lightning/shell.py
- pass the name parameter properly
- raise an exception if there is no existing VM with the given name
> shell: ensure the ssh action accept the name

- virt_lightning/shell.py
Restore the support for the `console` and `viewer` actions.
> shell: reenable the console and viewer actions

- tests/conftest.py
This to avoid the qemu-img call.
> test: mock hv.get_qcow_virtual_size()

- virt_lightning/api.py
- virt_lightning/shell.py
When running ``vl status``, new output should look like this 
```
💻 datastore       ⇛   centos@192.168.123.4 [centos-7]
💻 esxi1           ⇛   root@192.168.123.6 [esxi-6.7.0-20190802001-STANDARD]
💻 tst0            ⇛   username@192.168.123.5 [fedora-33]
💻 vcenter         ⇛   root@192.168.123.8 [VMware-VCSA-all-7.0.2-17694817]
```
> distro displayed in vl status output

- README.md
doc:
* Fix a typo: use `vl` instead of `vm`.
* add a link to `https://virt-lightning.org/`
> [doc] Fix a typo: use 'vl' instead of 'vm' & add link to https://virt-lightning.org/

- virt_lightning/shell.py
Do not raise a backtrace if a VM does not exist.
Closes: #212
> vl stop: no backtrace if VM does not exist

- virt_lightning/virt_lightning.py
This is much faster and works as expected.
note: Kubevirt already follows this strategy.
> metadata: use a virtio disk by default

- virt_lightning/shell.py
This includes one change that promotes two functions defined in closures to global, so that they don't need to be pasted in another CLI code.
There is also a dead elif that would never been executed that is removed by another commit.
> Slight CLI code moves

- virt_lightning/api.py
- virt_lightning/virt_lightning.py
- new key `meta_data_media_type` to expose cloud-init meta data through
a cdrom
- `default_bus_type` to switch between `ide`, `sata` and `virtio`.
> add support for legacy system without virtio

- README.md
- virt_lightning/api.py
A really simple implemention for additional disks. I used a dict for the config key `disks` for extensibility. Currently only qcow2 disks using the default pool can be created.
> add support for additional disks in VMs

- setup.py
I had a hard time to find the source. At first I read the website and then went to PyPI, but eventually I just searched using a search engine. This uses project_urls[1] in setup.py to add URLs on PyPI, which makes it easier to find the source.
[1]: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls
> Set the Source project URL in setup.py

- virt_lightning/virt_lightning.py
Current setup blocks snapshot creation for running instance
Closes: #272
> Change default "meta_data_media_type" to "cdrom"

- virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf
- virt-lightning.org/www/images/index.md
remove debian-testing image, link nolonger exists, and was based on debian-10
add debian-12 image
add debian-sid
cannot find current debian-testing/debian-13/debian-trixie image
> update debian images

- README.md
Closes #281 
pipx appears to seamlessly wrap up isolated python application.  feels a bit odd for a user install to require more packages (pipx) than a development setup but....
Figured differences were enough to break install into portions for REHL/Fedora and Debian/Ubuntu.
Changed an instance of apt-get to apt
removed merge conflict marker I stumbled across
Of note, pip3 install virt-lightning --break-system-packages is ~450 Mb clean to installed while pipx and build environment is ~850 Mb clean to installed, that kinda bothered me, but then I figured nobody is running this on a clean system, and if they are, they'll eventually want gcc and additional build utils right?
Tested on Ubuntu 23.10 VM's
Memory usage from : /usr/bin/time -v vl up ~ 60mb
Storage usage from : du -ah -d 1 …
> Update Readme installation instructions for Debian to use pipx

- tests/test_util.py
- virt_lightning/api.py
- virt_lightning/util.py
Replaces `distutils.util.strtobool` with a utility for Python 3.12 compatibility.
> Remove and replace distutils.util.strtobool

- tests/test_util.py
- virt-lightning.org/bench_images_startup.py
- virt_lightning/shell.py
This to address the following `ruff` error:
```
virt_lightning/shell.py:105:12: UP032 [*] Use f-string instead of `format` call
```
and a problem with up-to-date `black`.
> ruff: use f-string to format the fetch progress bar

- virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf
- virt-lightning.org/www/images/index.md
The official name of CentOS is CentOS Stream now. This should be reflected in the name of the images, IMHO.
It reads better too, at least to me.
This one fixes issue #304
> centos-n-stream renamed to centos-stream-n

- virt_lightning/api.py
Prevents inserting 'None' to inventory when additional NICs are not defined
> Fix for inventory template

- pyproject.toml
This to address the following warning:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
```
> pyproject: update ruff configuration key names

- virt-lightning.org/images.json
- virt-lightning.org/refresh.py
Without this, I get a `/bin/sh: /usr/bin/python3: not found` error when trying to run Ansible towards an OpenBSD 7.6 machine created using this tool. Overriding it in the inventory to use this path makes it work.
> refresh.py: Support overriding `python_interpreter` via `images_data.json`

- virt_lightning/api.py
- virt_lightning/shell.py
Replace the use of the Caddy service hosted at http://virt-lightning.org
with the `images.json` file introduced by 6e4fbb099d02b20ad61288789a16aa979386cfc6.
> fetch: don't use virt-lightning.org anymore

- README.md
- virt_lightning/api.py
- virt_lightning/configuration.py
- virt_lightning/shell.py
added support for a user defined json url, for cases where the needed distribution is not in the official json and a custom image repository is not necessary.
- to use add a custom_image_url in virt-lightning config
> add support for a user defined image list

- README.md
- virt_lightning/configuration.py
When `ssh_key_file` is empty, we now do a dynamic look up all the good
SSH key candidate in `~/.ssh/`.
Close: #320
> SSH key: dynamic file lookup
